config/routes.rb
Rails.application.routes.draw do
  root to: "organizers#index"
  
  get 'events', to: "events#index", as: "events"
  get 'events/new', to: "events#new"
  get 'events/show/:id', to: "events#show", as: "event"
  get 'events/search', to: "events#search"
  post 'events', to: "events#create"

  get 'organizers/index', to: "organizers#index"
  get 'organizers/new', to: "organizers#new", as: "new_organizer"
  get 'organizers/show/:id', to: "organizers#show", as: "organizer"
  post "organizers", to: "organizers#create"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  validates :street_num, presence: true
  validates :street, presence: true
  validates :suburb, presence: true
  validates :postcode, presence: true
  has_one :event, dependent: :destroy

  def full_name
    # 123 Street Road, Brisbane 4000
    return "#{street_num} #{street}, #{suburb} #{postcode}"
  end

  # validate :check_date_is_not_before

  # def check_date_is_not_before
  #   # return false if :date < Date.now
  # end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :address
  belongs_to :organizer

  validates :name, presence: true
  validates :time, presence: true
  validates :date, presence: true
end

app/models/organizer.rb
class Organizer < ApplicationRecord
  has_many :events, dependent: :destroy
  
  # validates_presence_of :email, :password
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
    @addresses = Address.all
    @organizers = Organizer.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def create
    # raise
    event = Event.new(event_params)
    redirect_to(event.save ? events_path : new_event_path)
  end

  def search
  end

  private 

  def event_params
    params.require(:event).permit(:name, :time, :date, :address_id)
  end
end

app/controllers/organizers_controller.rb
class OrganizersController < ApplicationController
  def index
    @organizers = Organizer.order(:email)
  end

  def new
    @organizer = Organizer.new
  end

  def show
    @organizer = Organizer.find(params[:id])
  end

  def create
    organizer = Organizer.new(organizer_params)
    redirect_to(organizer.save ? root_path : new_organizer_path)
  end

  private

  def organizer_params
    params.require(:organizer).permit(:email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/organizers_helper.rb
module OrganizersHelper
end

app/views/events/index.html.erb
<%= link_to "New", events_new_path %>
<% @events.each do |event| %>
  <h1><%= event.name %></h1>
  <h2>Date: <%= event.date %></h2>
  <h2>Time: <%= event.time %></h2>
  <h5>Organized by <%= event.organizer.email %></h5>
  <%= link_to "Show", event %>
<% end %>

app/views/events/new.html.erb
<%= form_for @event do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :time %>
    <%= form.time_field :time %>
  </div>
  <div>
    <%= form.label :date %>
    <%= form.date_field :date %>
  </div>
  <div>
    <%= form.label :address_id %>
    <%= form.collection_select :address_id, @addresses, :id, :full_name  %>
  </div>
  <div>
    <%= form.label :organizer_id %>
    <%= form.collection_select :organizer_id, @organizers, :id, :email  %>
  </div>
  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/events/search.html.erb
<h1>Events#search</h1>
<p>Find me in app/views/events/search.html.erb</p>

app/views/events/show.html.erb
  <h1><%= @event.name %></h1>
  <h2>Date: <%= @event.date %></h2>
  <h2>Time: <%= @event.time %></h2>
  <h5>Organized by {organizer}</h5>

  <%= link_to "Back", events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meetups</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/organizers/index.html.erb
<h1>Organizers</h1>
<%= link_to "New", new_organizer_path %>
<% @organizers.each do |organizer| %>
  <h2><%= organizer.email %></h2>
  <p>Joined: <%= organizer.created_at %></p>
  <%= link_to "Show", organizer %>
<% end %>

app/views/organizers/new.html.erb
<h1>Organizers#new</h1>
<p>Find me in app/views/organizers/new.html.erb</p>

<%= form_for @organizer do |form| %>
  <%= form.label :email %>
  <%= form.text_field :email %>
  <%= form.label :password %>
  <%= form.password_field :password %>
  <%= form.submit %>
<% end %>

app/views/organizers/show.html.erb
<h2><%= @organizer.email %></h2>
<p>Joined: <%= @organizer.created_at %></p>

<h2>Events:</h2>
<% @organizer.events.each do |event| %>
  <h1><%= event.name %></h1>
  <h2>Date: <%= event.date %></h2>
  <h2>Time: <%= event.time %></h2>
<% end %>